Repository cloudnativelabs/kube-router, pull requests merged in 2020-08, with the labels that each got.

#969 Sort Options
  pkg/options/options.go
Labels: code quality

#971 add IfaceHasNoAddr check for external ip delete error
  pkg/controllers/proxy/service_endpoints_sync.go
Labels: bug

#970 Permit ExternalIP on input
  docs/user-guide.md
  pkg/controllers/netpol/network_policy_controller.go
  pkg/controllers/netpol/network_policy_controller_test.go
  pkg/options/options.go
Labels: bug, enhancement
